# Generated by Django 3.0.6 on 2020-05-25 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_recommendation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='songtag',
            old_name='album',
            new_name='song',
        ),
    ]
