# Generated by Django 3.0.6 on 2020-05-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200525_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songtag',
            name='release_year',
            field=models.CharField(max_length=50),
        ),
    ]
