# Generated by Django 3.0.6 on 2020-06-24 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200525_1300'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recommendation',
        ),
    ]
